-- note 스키마 + SYS_USER (신규 빈 DB용)
-- EC2에서 DBeaver로 이미 만든 경우: Auth 기동 시 baseline-on-migrate 로 V1 은 스킵됨

CREATE SCHEMA IF NOT EXISTS note;

CREATE SEQUENCE IF NOT EXISTS note."USER_SEQ"
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS note."SYS_USER" (
    "USER_SEQ"       BIGINT       NOT NULL DEFAULT nextval('note."USER_SEQ"'::regclass),
    "USER_ID"        VARCHAR(64)  NOT NULL,
    "MAIL_ADDRESS"   VARCHAR(255) NOT NULL,
    "PASSWORD_HASH"  VARCHAR(255),
    "AUTH_PROVIDER"  VARCHAR(20)  NOT NULL,
    "EXTERNAL_ID"    VARCHAR(255),
    "EXTERNAL_EMAIL" VARCHAR(255),
    "STATUS"         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT"     TIMESTAMP    NOT NULL DEFAULT NOW(),
    "UPDATED_AT"     TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_SYS_USER" PRIMARY KEY ("USER_SEQ"),
    CONSTRAINT "UQ_SYS_USER_USER_ID" UNIQUE ("USER_ID"),
    CONSTRAINT "UQ_SYS_USER_MAIL_ADDRESS" UNIQUE ("MAIL_ADDRESS")
);

ALTER SEQUENCE note."USER_SEQ" OWNED BY note."SYS_USER"."USER_SEQ";

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_SYS_USER_PROVIDER_EXTERNAL"
    ON note."SYS_USER" ("AUTH_PROVIDER", "EXTERNAL_ID")
    WHERE "EXTERNAL_ID" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IDX_SYS_USER_STATUS"
    ON note."SYS_USER" ("STATUS");

GRANT USAGE ON SCHEMA note TO note;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA note TO note;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA note TO note;
ALTER DEFAULT PRIVILEGES IN SCHEMA note
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO note;
ALTER DEFAULT PRIVILEGES IN SCHEMA note
    GRANT USAGE, SELECT ON SEQUENCES TO note;
