-- SYS_USER 감사 컬럼 + soft delete (탈퇴)
-- DEL_YN='Y' 행은 조회에서 제외. userId/mail 재가입을 위해 유니크는 활성 행만.

ALTER TABLE note."SYS_USER"
    ADD COLUMN IF NOT EXISTS "CREATED_BY" BIGINT,
    ADD COLUMN IF NOT EXISTS "UPDATED_BY" BIGINT,
    ADD COLUMN IF NOT EXISTS "DEL_YN"     CHAR(1) NOT NULL DEFAULT 'N',
    ADD COLUMN IF NOT EXISTS "DELETED_AT" TIMESTAMP;

ALTER TABLE note."SYS_USER" DROP CONSTRAINT IF EXISTS "UQ_SYS_USER_USER_ID";
ALTER TABLE note."SYS_USER" DROP CONSTRAINT IF EXISTS "UQ_SYS_USER_MAIL_ADDRESS";

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_SYS_USER_USER_ID"
    ON note."SYS_USER" ("USER_ID")
    WHERE "DEL_YN" = 'N';

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_SYS_USER_MAIL_ADDRESS"
    ON note."SYS_USER" ("MAIL_ADDRESS")
    WHERE "DEL_YN" = 'N';

DROP INDEX IF EXISTS note."UQ_SYS_USER_PROVIDER_EXTERNAL";

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_SYS_USER_PROVIDER_EXTERNAL"
    ON note."SYS_USER" ("AUTH_PROVIDER", "EXTERNAL_ID")
    WHERE "EXTERNAL_ID" IS NOT NULL AND "DEL_YN" = 'N';
