-- 앱 주소록: 연락처 / 그룹 / 멤버 / 그룹 공유

CREATE SEQUENCE IF NOT EXISTS note."CONTACT_SEQ"
    AS BIGINT START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE IF NOT EXISTS note."CONTACT_GROUP_SEQ"
    AS BIGINT START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE SEQUENCE IF NOT EXISTS note."CONTACT_GROUP_SHARE_SEQ"
    AS BIGINT START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS note."MAIL_CONTACT" (
    "CONTACT_SEQ"    BIGINT       NOT NULL DEFAULT nextval('note."CONTACT_SEQ"'::regclass),
    "USER_SEQ"       BIGINT       NOT NULL,
    "DISPLAY_NAME"   VARCHAR(120),
    "EMAIL"          VARCHAR(255) NOT NULL,
    "CREATED_AT"     TIMESTAMP    NOT NULL DEFAULT NOW(),
    "UPDATED_AT"     TIMESTAMP    NOT NULL DEFAULT NOW(),
    "CREATED_BY"     BIGINT,
    "UPDATED_BY"     BIGINT,
    "DEL_YN"         VARCHAR(1)   NOT NULL DEFAULT 'N',
    "DELETED_AT"     TIMESTAMP,
    CONSTRAINT "PK_MAIL_CONTACT" PRIMARY KEY ("CONTACT_SEQ"),
    CONSTRAINT "FK_MAIL_CONTACT_USER" FOREIGN KEY ("USER_SEQ")
        REFERENCES note."SYS_USER" ("USER_SEQ")
);

ALTER SEQUENCE note."CONTACT_SEQ" OWNED BY note."MAIL_CONTACT"."CONTACT_SEQ";

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MAIL_CONTACT_USER_EMAIL"
    ON note."MAIL_CONTACT" ("USER_SEQ", lower("EMAIL"))
    WHERE "DEL_YN" = 'N';

CREATE INDEX IF NOT EXISTS "IDX_MAIL_CONTACT_USER"
    ON note."MAIL_CONTACT" ("USER_SEQ")
    WHERE "DEL_YN" = 'N';

CREATE TABLE IF NOT EXISTS note."MAIL_CONTACT_GROUP" (
    "GROUP_SEQ"        BIGINT       NOT NULL DEFAULT nextval('note."CONTACT_GROUP_SEQ"'::regclass),
    "OWNER_USER_SEQ"   BIGINT       NOT NULL,
    "NAME"             VARCHAR(120) NOT NULL,
    "CREATED_AT"       TIMESTAMP    NOT NULL DEFAULT NOW(),
    "UPDATED_AT"       TIMESTAMP    NOT NULL DEFAULT NOW(),
    "CREATED_BY"       BIGINT,
    "UPDATED_BY"       BIGINT,
    "DEL_YN"           VARCHAR(1)   NOT NULL DEFAULT 'N',
    "DELETED_AT"       TIMESTAMP,
    CONSTRAINT "PK_MAIL_CONTACT_GROUP" PRIMARY KEY ("GROUP_SEQ"),
    CONSTRAINT "FK_MAIL_CONTACT_GROUP_OWNER" FOREIGN KEY ("OWNER_USER_SEQ")
        REFERENCES note."SYS_USER" ("USER_SEQ")
);

ALTER SEQUENCE note."CONTACT_GROUP_SEQ" OWNED BY note."MAIL_CONTACT_GROUP"."GROUP_SEQ";

CREATE INDEX IF NOT EXISTS "IDX_MAIL_CONTACT_GROUP_OWNER"
    ON note."MAIL_CONTACT_GROUP" ("OWNER_USER_SEQ")
    WHERE "DEL_YN" = 'N';

CREATE TABLE IF NOT EXISTS note."MAIL_CONTACT_GROUP_MEMBER" (
    "GROUP_SEQ"    BIGINT NOT NULL,
    "CONTACT_SEQ"  BIGINT NOT NULL,
    "CREATED_AT"   TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_MAIL_CONTACT_GROUP_MEMBER" PRIMARY KEY ("GROUP_SEQ", "CONTACT_SEQ"),
    CONSTRAINT "FK_MAIL_CGM_GROUP" FOREIGN KEY ("GROUP_SEQ")
        REFERENCES note."MAIL_CONTACT_GROUP" ("GROUP_SEQ"),
    CONSTRAINT "FK_MAIL_CGM_CONTACT" FOREIGN KEY ("CONTACT_SEQ")
        REFERENCES note."MAIL_CONTACT" ("CONTACT_SEQ")
);

CREATE TABLE IF NOT EXISTS note."MAIL_CONTACT_GROUP_SHARE" (
    "SHARE_SEQ"              BIGINT      NOT NULL DEFAULT nextval('note."CONTACT_GROUP_SHARE_SEQ"'::regclass),
    "GROUP_SEQ"              BIGINT      NOT NULL,
    "SHARED_WITH_USER_SEQ"   BIGINT      NOT NULL,
    "PERMISSION"             VARCHAR(10) NOT NULL,
    "CREATED_AT"             TIMESTAMP   NOT NULL DEFAULT NOW(),
    "UPDATED_AT"             TIMESTAMP   NOT NULL DEFAULT NOW(),
    "CREATED_BY"             BIGINT,
    "UPDATED_BY"             BIGINT,
    "DEL_YN"                 VARCHAR(1)  NOT NULL DEFAULT 'N',
    "DELETED_AT"             TIMESTAMP,
    CONSTRAINT "PK_MAIL_CONTACT_GROUP_SHARE" PRIMARY KEY ("SHARE_SEQ"),
    CONSTRAINT "FK_MAIL_CGS_GROUP" FOREIGN KEY ("GROUP_SEQ")
        REFERENCES note."MAIL_CONTACT_GROUP" ("GROUP_SEQ"),
    CONSTRAINT "FK_MAIL_CGS_USER" FOREIGN KEY ("SHARED_WITH_USER_SEQ")
        REFERENCES note."SYS_USER" ("USER_SEQ"),
    CONSTRAINT "CK_MAIL_CGS_PERMISSION" CHECK ("PERMISSION" IN ('READ', 'WRITE'))
);

ALTER SEQUENCE note."CONTACT_GROUP_SHARE_SEQ" OWNED BY note."MAIL_CONTACT_GROUP_SHARE"."SHARE_SEQ";

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MAIL_CGS_GROUP_USER"
    ON note."MAIL_CONTACT_GROUP_SHARE" ("GROUP_SEQ", "SHARED_WITH_USER_SEQ")
    WHERE "DEL_YN" = 'N';

GRANT SELECT, INSERT, UPDATE, DELETE ON note."MAIL_CONTACT" TO note;
GRANT SELECT, INSERT, UPDATE, DELETE ON note."MAIL_CONTACT_GROUP" TO note;
GRANT SELECT, INSERT, UPDATE, DELETE ON note."MAIL_CONTACT_GROUP_MEMBER" TO note;
GRANT SELECT, INSERT, UPDATE, DELETE ON note."MAIL_CONTACT_GROUP_SHARE" TO note;
GRANT USAGE, SELECT ON note."CONTACT_SEQ" TO note;
GRANT USAGE, SELECT ON note."CONTACT_GROUP_SEQ" TO note;
GRANT USAGE, SELECT ON note."CONTACT_GROUP_SHARE_SEQ" TO note;
