-- 그룹 멤버는 한 테이블. 행마다 MAIL_CONTACT 또는 SYS_USER 중 하나만 가리킨다.

CREATE SEQUENCE IF NOT EXISTS note."CONTACT_GROUP_MEMBER_SEQ"
    AS BIGINT START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ADD COLUMN IF NOT EXISTS "MEMBER_SEQ" BIGINT,
    ADD COLUMN IF NOT EXISTS "MEMBER_USER_SEQ" BIGINT;

UPDATE note."MAIL_CONTACT_GROUP_MEMBER"
SET "MEMBER_SEQ" = nextval('note."CONTACT_GROUP_MEMBER_SEQ"')
WHERE "MEMBER_SEQ" IS NULL;

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ALTER COLUMN "MEMBER_SEQ" SET DEFAULT nextval('note."CONTACT_GROUP_MEMBER_SEQ"'::regclass),
    ALTER COLUMN "MEMBER_SEQ" SET NOT NULL;

ALTER SEQUENCE note."CONTACT_GROUP_MEMBER_SEQ" OWNED BY note."MAIL_CONTACT_GROUP_MEMBER"."MEMBER_SEQ";

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    DROP CONSTRAINT IF EXISTS "PK_MAIL_CONTACT_GROUP_MEMBER";

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ADD CONSTRAINT "PK_MAIL_CONTACT_GROUP_MEMBER" PRIMARY KEY ("MEMBER_SEQ");

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ALTER COLUMN "CONTACT_SEQ" DROP NOT NULL;

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    DROP CONSTRAINT IF EXISTS "FK_MAIL_CGM_USER";

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ADD CONSTRAINT "FK_MAIL_CGM_USER" FOREIGN KEY ("MEMBER_USER_SEQ")
        REFERENCES note."SYS_USER" ("USER_SEQ");

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    DROP CONSTRAINT IF EXISTS "CK_MAIL_CGM_XOR";

ALTER TABLE note."MAIL_CONTACT_GROUP_MEMBER"
    ADD CONSTRAINT "CK_MAIL_CGM_XOR" CHECK (
        ("CONTACT_SEQ" IS NOT NULL AND "MEMBER_USER_SEQ" IS NULL)
        OR ("CONTACT_SEQ" IS NULL AND "MEMBER_USER_SEQ" IS NOT NULL)
    );

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MAIL_CGM_GROUP_CONTACT"
    ON note."MAIL_CONTACT_GROUP_MEMBER" ("GROUP_SEQ", "CONTACT_SEQ")
    WHERE "CONTACT_SEQ" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_MAIL_CGM_GROUP_USER"
    ON note."MAIL_CONTACT_GROUP_MEMBER" ("GROUP_SEQ", "MEMBER_USER_SEQ")
    WHERE "MEMBER_USER_SEQ" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IDX_MAIL_CGM_GROUP"
    ON note."MAIL_CONTACT_GROUP_MEMBER" ("GROUP_SEQ");

-- 이전에 복사해 둔 SYS_USER 연락처 멤버는 USER_SEQ로 바꾼다.
UPDATE note."MAIL_CONTACT_GROUP_MEMBER" m
SET "MEMBER_USER_SEQ" = u."USER_SEQ",
    "CONTACT_SEQ" = NULL
FROM note."MAIL_CONTACT" c
INNER JOIN note."SYS_USER" u
    ON lower(u."MAIL_ADDRESS") = lower(c."EMAIL")
   AND u."DEL_YN" = 'N'
WHERE m."CONTACT_SEQ" = c."CONTACT_SEQ"
  AND m."MEMBER_USER_SEQ" IS NULL;

DO $$
BEGIN
    IF to_regclass('note."MAIL_CONTACT_GROUP_ACCOUNT_MEMBER"') IS NOT NULL THEN
        INSERT INTO note."MAIL_CONTACT_GROUP_MEMBER" ("GROUP_SEQ", "MEMBER_USER_SEQ", "CREATED_AT")
        SELECT a."GROUP_SEQ", a."MEMBER_USER_SEQ", a."CREATED_AT"
        FROM note."MAIL_CONTACT_GROUP_ACCOUNT_MEMBER" a
        WHERE NOT EXISTS (
            SELECT 1
            FROM note."MAIL_CONTACT_GROUP_MEMBER" m
            WHERE m."GROUP_SEQ" = a."GROUP_SEQ"
              AND m."MEMBER_USER_SEQ" = a."MEMBER_USER_SEQ"
        );
        DROP TABLE note."MAIL_CONTACT_GROUP_ACCOUNT_MEMBER";
    END IF;
END $$;

UPDATE note."MAIL_CONTACT" c
SET "DEL_YN" = 'Y',
    "DELETED_AT" = NOW(),
    "UPDATED_AT" = NOW()
WHERE c."DEL_YN" = 'N'
  AND EXISTS (
      SELECT 1
      FROM note."SYS_USER" u
      WHERE u."DEL_YN" = 'N'
        AND lower(u."MAIL_ADDRESS") = lower(c."EMAIL")
  );

GRANT USAGE, SELECT ON note."CONTACT_GROUP_MEMBER_SEQ" TO note;
